server:
  port: 9000

eureka:
  instance:
    hostname: discovery-service
    port: 8082
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:mysql://mysql-auth:3306/heimdall-auth?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver