server:
  servlet:
    context-path: /uaa
  port: 9000

eureka:
  instance:
    hostname: discovery-service
    port: 8082
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: heimdall
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write
            
spring:
  data:
    mongodb:
      uri: mongodb+srv://heimdall:heimdall@heimdall-ikxkk.mongodb.net/test
      database: heimdall-auth

