server:
  servlet:
    context-path: /uaa
  port: 9000
         
spring:
  data:
    mongodb:
      uri: mongodb+srv://heimdall:heimdall@heimdall-ikxkk.mongodb.net/test
      database: heimdall-auth

