server:
  servlet:
    context-path: /heimdall
  port: 8086

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

spring:
  data:
    mongodb:
      host: mongo-heimdall
      username: heimdall
      password: heimdall
      database: heimdall
      port: 27017
feign:
  hystrix:
    enabled: true

