server:
  servlet:
    context-path: /heimdall
  port: 8086

spring:
  data:
    mongodb:
      host: mongo-heimdall
      username: heimdall
      password: heimdall
      database: heimdall
      port: 27017
feign:
  hystrix:
    enabled: true

